### ISSUE TITLE
pulse doesn't work with backgroundColor anymore

### ISSUE THREAD

**Issue by ghost** [padolsey-archive/jquery.fn#8]
See http://jsbin.com/iqujo/58. Which parameters do still work? opacity, ok, what else?

**Comment by padolsey** [comment]
You need the jQuery color plugin if you want to animate colours. 

http://plugins.jquery.com/files/jquery.color.js.txt

**Comment by ghost** [comment]
Am 31.10.2011 12:58, schrieb James Padolsey:

> You need the jQuery color plugin if you want to animate colours.
> 
> http://plugins.jquery.com/files/jquery.color.js.txt
> 
> thanks for the hint!
